name: cd

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5

      - name: Build
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Docker build'
        run: docker build -t nsmith7989/notely:latest .

      - name: 'Deploy'
        # us-central1-docker.pkg.dev/notely-484901/notely-ar-repo
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-484901/notely-ar-repo/noteley:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-484901/notely-ar-repo/noteley:latest --region us-central1 --allow-unauthenticated --project notely-484901 --max-instances=4
